STATQ/GMaps/routes.py
import os

import boto3
from flask import render_template, Blueprint
from flask_googlemaps import Map

from STATQ import s3

GMaps = Blueprint('GMaps', __name__)


@GMaps.route('/Kort/Målestationer/')
def mapview():
    Filsti = s3.get_object(Bucket=os.environ.get('S3_BUCKET_NAME'), Key=str('Alle Data/Maalestationer_liste.txt'))
    body = Filsti['Body'].read().decode()
    # print(body)
    marker_liste = []
    icon_url = 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'
    Firstline = 1
    for lines in body.split("\n"):
        parts = lines.split("\t")
        if Firstline == 0:
            try:
                vandloeb = parts[0]
                vandloeb_og_sted = parts[1]
                sted = vandloeb_og_sted.split(',')[1][1:]
                marker_liste.append(dict({
                    'lat': float(parts[-1]),
                    'lng': float(parts[-2]),
                    'infobox': f"""<b>{vandloeb_og_sted}<b><br> <a href='/redirect/{vandloeb}/{sted}'> Se data </a>""",
                    'icon': icon_url
                }))
            except IndexError:
                Damn = 1
                # print(lines)
        Firstline = 0

    # creating a map in the view

    sndmap = Map(
        zoom=7.5,
        identifier="sndmap",
        lat=56.1985,
        lng=10.0482,
        style="height:82vh;width:73.6vw;margin:0;",  # hardcoded!
        markers=marker_liste
    )

    return render_template('map.html', sndmap=sndmap)


@GMaps.route('/redirect/<string:vandloeb>/<string:valgt_sted>')
def station_chosen(vandloeb, valgt_sted):
    filename = vandloeb
    # Creating grouped-tuple to go to proces file.
    s3_resource = boto3.resource('s3')
    my_bucket = s3_resource.Bucket(os.environ.get('S3_BUCKET_NAME'))
    files = my_bucket.objects.filter(Prefix=str('Alle Data/') + str(filename) + '/')
    filnavne = []
    Q = []
    H = []
    stationer = []
    for objects in files:
        sep = '_'  # The separator fx FLADBRO KRO_VANDFORING.csv.
        obj = objects.key
        obj = obj.removeprefix('Alle Data/' + str(filename) + '/')
        stationer.append(obj)
    one_group = [];
    grouped = []
    steder = list(set([x.split('_', 1)[0] for x in stationer]))
    QH_name = None
    for sted in steder:
        if sted.split(',')[1][1:] == valgt_sted:  #

            if f'{sted}_VANDSTAND.csv' in stationer:

                H_filename = f'{vandloeb}, {valgt_sted}_VANDSTAND.csv'
                H_name = ('Vandstand')
            else:

                H_name = ('Ingen Vandstand')
                H_filename = '#'

            if f'{sted}_VANDFORING.csv' in stationer:

                Q_filename = f'{vandloeb}, {valgt_sted}_VANDFORING.csv'
                print(Q_filename)
                Q_name = ('Vandføring')

            else:

                Q_name = ('Ingen Vandføring')
                Q_filename = '#'

            if Q_filename != '#' and H_filename != '#':

                QH_name = 'Se QH-kurver'

            else:

                if Q_filename == '#':

                    mangel = 'Ingen vandføringsdata'

                elif H_filename == '#':

                    mangel = 'Ingen vandstandsdata'

                QH_name = 'QH kurver ikke tilgængelige (%s)' % (mangel)
    try:
        stednavn = valgt_sted.split(';')[1][:]
    except IndexError:
        stednavn = valgt_sted
    grouped.append([stednavn, H_name, H_filename, Q_name, Q_filename, QH_name])
    return render_template('program/one_station_file.html', stationer=stationer, Vandloeb=filename, grouped=grouped,
                           QH_name=QH_name)

STATQ/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html', title='About')

STATQ/users/routes.py
import os

from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required

from STATQ import db, bcrypt
from STATQ.models import User
from STATQ.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                               RequestResetForm, ResetPasswordForm)
from STATQ.users.utils import send_reset_email

users = Blueprint('users', __name__)


# program = Blueprint('program', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Din konto er nu oprettet! Du kan nu logge ind.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Logind fejlet. Kontrollér email og kodeord', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        new_path = current_app.root_path + '/static/files/' + current_user.username + '/'
        try:
            os.rename(old_path, new_path)
        except FileExistsError:
            pass
        flash('Din konto er nu opdateret!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@users.route("/nulstil_kodeord", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Instruktioner til nulstilling af kodeord er blevet sendt til din email', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Nulstil kodeord',
                           form=form)


@users.route("/nulstil_kodeord/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Dette er en udløbet eller ugyldig token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Dit kodeord er blevet opdateret! Du kan nu logge ind', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Nulstil kodeord', form=form)

STATQ/templates/about.html
{% extends "layout.html" %}
{% block content %}
<h1>About Page</h1>
{% endblock content %}

STATQ/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <h1 style="font-size: 5vmin">Opdatér email</h1>
    <form action="" enctype="multipart/form-data" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group" style="font-size: 3vmin">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

STATQ/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="front" style="font-size: 7vmin">VELKOMMEN TIL STATQ
    <p style=" font-size: 2vmin"> En portal med de nyeste hydrometri-data fra den offentlige data-portal ODA FOR
        ALLE.</p>
    <p style=" font-size: 2vmin">Opret en bruger og gå på udkig i Databasen </p></div>
{% endblock content %}

STATQ/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">

    <!-- Bootstrap CSS -->
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css">
    {% if title %}
    <title>STATQ - {{ title }}</title>
    {% else %}
    <title>STATQ</title>
    {% endif %}

</head>

<body class="bg-image">
<div class="sidebar">
    <div class="sidebar-header" style="text-decoration: none;">
        <a class="sideheader" href="{{ url_for('main.home') }}" style="text-decoration: none;">
            STATQ
        </a>
    </div>
    <li class="nav" style="">
        <div class="sidebar-content">
            <a class="side" href="{{ url_for('GMaps.mapview') }}">
                Find på Kort
            </a>
        </div>
        <!--         <div class="sidebar-content">
                  <a class="side" href="{{ url_for('program.your_files') }}">
                      Filer
                  </a>
                </div> -->
        <div class="sidebar-content">
            <a class="side" href="{{ url_for('program.database') }}">
                Databasen
            </a>
        </div>
        <div class="sidebar-content">
            <a class="side" href="{{ url_for('program.help') }}">
                FAQ
            </a>
        </div>
    </li>
</div>
<!--
<div class="login-trigger-row">
    {% if current_user.is_authenticated %}
    <a class="logout-trigger" href="{{ url_for('users.logout') }}">Log ud</a>
    <a class="login-trigger" href="{{ url_for('users.account') }}">Bruger</a>
    {% else %}
    <a class="login-trigger" href="{{ url_for('users.register') }}" style="float: right">Opret</a>
    <a class="login-trigger" href="{{ url_for('users.login') }}" style="float: right">Log ind</a>

    {% endif %}
</div> -->
<div class="container" style="top: .5vh">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</div>

<div class="bg-image"></div>
<div class="blur"></div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script crossorigin="anonymous"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script crossorigin="anonymous"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

STATQ/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <h2 style="font-size: 5vmin;"><u style="color: #004b8d; font-weight: bold; text-decoration-color:gainsboro"> Log
            ind </u></h2>

        <fieldset class="form-group">
            <div class="form-group">
                {{ form.email.label(class="form-control-label", style="font-size: 3vmin") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid", placeholder="test") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label", style="font-size: 3vmin") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback" style="left: 18.5vw; top: 22vh">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-info", style="font-size: 2.5vmin") }}<br>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}" style="font-size: 2.5vmin">Glemt kodeord?</a>
            </small>
        </div>
    </form>
</div>
{% endblock content %}

STATQ/templates/map.html
{% extends "layout.html" %}
{% block content %}
<body>
<div class="content-section" style="font-size: 2.7vmin">
    <h1 style="color: rgba(1,1,1)"> Kort over målestationer </h1>
    {{sndmap.js}}
    {{sndmap.html}}
</div>
</body>
{% endblock content %}

STATQ/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section" style="font-size: 2.7vmin">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <h2 style="font-size: 5vmin;"><u style="color: #004b8d; font-weight: bold; text-decoration-color:gainsboro">
                Opret bruger </u></h2>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-info") }}
        </div>
    </form>
</div>
{% endblock content %}

STATQ/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Nulstil kodeord</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

STATQ/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Nulstil kodeord</legend>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}