STATQ/program/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, BooleanField, FloatField
from wtforms.validators import DataRequired


class UploadFileForm(FlaskForm):
    file = FileField(label='Tryk her eller træk fil til feltet',
                     validators=[DataRequired(), FileAllowed(['csv', 'txt'])])
    submit = SubmitField('Upload')
    plotsubmit = SubmitField('Se Plot')
    plotstr = StringField()
    per_year = BooleanField('Vis Min, med og maks for hvert år')
    Qm_yr = FloatField();
    Qm_s = FloatField();
    Qm_v = FloatField();
    Qmin_yr = FloatField();
    Qmin_s = FloatField();
    Qmin_v = FloatField();
    Qmax_yr = FloatField();
    Qmax_s = FloatField();
    Qmax_v = FloatField();


# class ProcesFileForm(FlaskForm):

class ProcesFileForm(FlaskForm):
    Qm_yr = FloatField();
    Qm_s = FloatField();
    Qm_v = FloatField();
    Qmin_yr = FloatField();
    Qmin_s = FloatField();
    Qmin_v = FloatField();
    Qmax_yr = FloatField();
    Qmax_s = FloatField();
    Qmax_v = FloatField();
    rawplotstr = StringField()
    seasonplotstr = StringField()
    enkeltaarsplotstr = StringField()
    oneyearplotstr = StringField()
    Lokalitet = StringField()

STATQ/program/routes.py
import io
import os

import boto3
from flask import render_template, request, Blueprint, redirect, current_app, flash, url_for
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename

from STATQ import s3
from STATQ.program.forms import ProcesFileForm
from STATQ.program.utils import (parse_data, parse_databasedata,
                                 plotly_hydro, plotly_QH, plotly_kemi, plotly_season, plotly_bar, plotly_stoftransport)

program = Blueprint('program', __name__)


@program.route('/StatQ/dine-filer/', methods=['GET', 'POST'])
@login_required
def upload_file():
    s3_resource = boto3.resource('s3')
    my_bucket = s3_resource.Bucket(os.environ.get('S3_BUCKET_NAME'))
    files = my_bucket.objects.filter(Prefix=str(current_user.username) + "/")
    filenames = []
    for objects in files:
        obj = objects.key
        obj = obj.removeprefix(str(current_user.username) + '/')
        filenames.append(obj)
    user_folder = current_user.username + '/'

    if request.files:
        file = request.files['myFile']
        if file.filename == "":
            flash("Filen skal have et navn", 'danger')
            return redirect(request.url)

        if not allowed_filetype(file.filename):
            flash("Filtype er ikke understøttet", 'danger')
            return redirect(request.url)

        else:
            filename = secure_filename(file.filename)
        try:
            s3.upload_fileobj(file, 'statq-bucket', str(user_folder) + str(filename))
        except Exception as e:
            flash("Noget gik galt: " + e, 'danger')
        # s3_resource.meta.client.upload_file(str(file.filename), 'statq-bucket',str(user_folder)+str(filename))
        flash("Fil er uploadet", 'success')
        return redirect(url_for('program.your_files'))

    return render_template('program/proces_file.html', files=files, filenames=filenames)


@program.route('/StatQ/dine-filer/', methods=['GET', 'POST'])
@login_required
def your_files():
    s3_resource = boto3.resource('s3')
    my_bucket = s3_resource.Bucket(os.environ.get('S3_BUCKET_NAME'))
    files = my_bucket.objects.filter(Prefix=str(current_user.username) + "/")
    return render_template('program/proces_file.html', files=files, filepaths=filepaths)


@program.route('/StatQ/dine-filer/<string:filename>/slet-fil')
@login_required
def delete_file(filename):
    s3.delete_object(Bucket=os.environ.get('S3_BUCKET_NAME'), Key=str(current_user.username) + '/' + str(filename))
    flash(str(filename) + " er blevet slettet", 'success')
    return redirect(url_for('program.your_files'))


@program.route('/StatQ/dine-filer/<string:filename>', methods=['GET', 'POST'])
@login_required
def proces_file(filename):
    form = ProcesFileForm
    file = s3.get_object(Bucket=os.environ.get('S3_BUCKET_NAME'), Key=str(current_user.username) + '/' + str(filename))
    df = parse_data(io.BytesIO(file['Body'].read()))
    if isinstance(df, str):
        flash(df, 'danger')
        return redirect(url_for('program.your_files'))
    if type(df) == list:
        graphJSONseason = plotly_stoftransport(df)
        # file_path = io.BytesIO(file['Body'].read())
        # print(file_path)
        # new_df = pd.read_csv(file_path, encoding = "ISO-8859-1", decimal=',', delimiter=";")
        # newsub_df = df.head(1)
        # newsub_df.pop("År")
        # newsub_df.pop("Måned")
        # newsub_df.pop("Resultat")

        # headings = list(newsub_df.columns)
        # information = list(newsub_df.iloc[0])
        headings = ['Filbeskrivelse ']
        information = ['Kommer snart']
        infolist = zip(headings, information)
        graphJSONraw = None
    else:
        sub_df = df.head(1)
        sub_df.pop("Resultat")
        # parameters = str(set(df['Parameter']))
        # sub_df['Parameter'] = parameters
        headings = list(sub_df.columns)
        information = list(sub_df.iloc[0])

        infolist = zip(headings, information)
        string_test = str(df['Parameter'].iloc[0])
        cond1 = 'Vandføring'
        cond2 = 'Vandstand'

        if string_test == cond1 or string_test == cond2:
            graphJSONseason = plotly_season(df)
            graphJSONraw = plotly_hydro(df)
            graphJSONbar = plotly_bar(df)
        elif string_test != cond1 and string_test != cond2:
            graphJSONseason = None
            graphJSONbar = None
            graphJSONraw = plotly_kemi(df)

    return render_template('program/file_results.html', graphJSONbar=graphJSONbar, graphJSONraw=graphJSONraw,
                           graphJSONseason=graphJSONseason, form=form, infolist=infolist, filename=filename)


@program.route('/StatQ/database/<string:Vandloeb>/<string:filename>', methods=['GET', 'POST'])
# @login_required
def proces_databasefile(Vandloeb, filename):
    sted = filename
    print(sted)
    # filename = filename.split(",")[1][1:].replace(";",",")
    # print(filename)
    if filename == '#':
        flash('De ønskede data findes ikke...', 'danger')
        return redirect(url_for('program.station_files', filename=Vandloeb))
    form = ProcesFileForm
    file = s3.get_object(Bucket=os.environ.get('S3_BUCKET_NAME'),
                         Key=str('Alle Data/') + str(Vandloeb) + '/' + str(sted))
    df = parse_databasedata(io.BytesIO(file['Body'].read()))
    if isinstance(df, str):
        flash(df, 'danger')
        return redirect(url_for('program.your_files'))
    if type(df) == list:
        graphJSONseason = plotly_stoftransport(df)
        # file_path = io.BytesIO(file['Body'].read())
        # print(file_path)
        # new_df = pd.read_csv(file_path, encoding = "ISO-8859-1", decimal=',', delimiter=";")
        # newsub_df = df.head(1)
        # newsub_df.pop("År")
        # newsub_df.pop("Måned")
        # newsub_df.pop("Resultat")

        # headings = list(newsub_df.columns)
        # information = list(newsub_df.iloc[0])
        headings = ['Filbeskrivelse ']
        information = ['Kommer snart']
        infolist = zip(headings, information)
        graphJSONraw = None
    else:
        sub_df = df.head(1)
        sub_df.pop("Resultat")
        # parameters = str(set(df['Parameter']))
        # sub_df['Parameter'] = parameters
        headings = list(sub_df.columns)
        information = list(sub_df.iloc[0])

        infolist = zip(headings, information)
        string_test = str(df['Parameter'].iloc[0])
        cond1 = 'Vandføring'
        cond2 = 'Vandstand'

        if string_test == cond1 or string_test == cond2:
            graphJSONseason = plotly_season(df)
            graphJSONraw = plotly_hydro(df)
            graphJSONbar = plotly_bar(df)
        elif string_test != cond1 and string_test != cond2:
            graphJSONseason = None
            graphJSONbar = None
            graphJSONraw = plotly_kemi(df)

    return render_template('program/file_results.html', graphJSONbar=graphJSONbar, graphJSONraw=graphJSONraw,
                           graphJSONseason=graphJSONseason, form=form, infolist=infolist, filename=filename)


@program.route('/StatQ/database/<string:Vandloeb>/QH-kurver/<string:Q_file>/<string:H_file>/', methods=['GET', 'POST'])
# @login_required
def proces_databaseQH(Vandloeb, Q_file, H_file):
    if Q_file == '#' or H_file == '#':
        flash('De ønskede data findes ikke...', 'danger')
        return redirect(url_for('program.station_files', filename=Vandloeb))
    form = ProcesFileForm
    Q_file = s3.get_object(Bucket=os.environ.get('S3_BUCKET_NAME'),
                           Key=str('Alle Data/') + str(Vandloeb) + '/' + str(Q_file))
    Q = parse_databasedata(io.BytesIO(Q_file['Body'].read()))
    H_file = s3.get_object(Bucket=os.environ.get('S3_BUCKET_NAME'),
                           Key=str('Alle Data/') + str(Vandloeb) + '/' + str(H_file))
    H = parse_databasedata(io.BytesIO(H_file['Body'].read()))
    graphJSONQH = plotly_QH(Q, H)
    return render_template('program/QH_results.html', graphJSONQH=graphJSONQH)


@program.route('/StatQ/kom-godt-i-gang')
def kom_godt_i_gang():
    return render_template('program/kom-godt-i-gang.html')


@program.route('/StatQ/database')
# @login_required
def database():
    s3_resource = boto3.resource('s3')
    my_bucket = s3_resource.Bucket(os.environ.get('S3_BUCKET_NAME'))
    Q_files = my_bucket.objects.filter(Prefix="/Alle Data/Q/")
    Q_filenames = []
    for objects in Q_files:
        obj = objects.key
        obj = obj.removeprefix('/')
        Q_filenames.append(obj)
    H_files = my_bucket.objects.filter(Prefix="/Alle Data/H/")
    H_filenames = []
    for objects in H_files:
        obj = objects.key
        obj = obj.removeprefix('/')
        H_filenames.append(obj)
        print(H_filenames)
    s3 = boto3.client('s3')

    Q_path = s3.get_object(Bucket=os.environ.get('S3_BUCKET_NAME'), Key=str('Alle Data/Q_stationer.txt'))

    filestr = Q_path['Body'].read().decode('latin-1')
    Q_files = filestr.split("\n")
    Q_files = sorted([x.strip('\r') for x in Q_files])

    H_path = s3.get_object(Bucket=os.environ.get('S3_BUCKET_NAME'), Key=str('Alle Data/Q_stationer.txt'))
    filestr = H_path['Body'].read().decode('latin-1')
    H_files = filestr.split("\n")
    H_files = sorted([x.strip('\r') for x in H_files])

    return render_template('program/database.html', Q_filenames=Q_filenames, H_filenames=H_filenames, Q_files=Q_files,
                           H_files=H_files)


@program.route('/StatQ/database/<string:filename>')
def station_files(filename):
    s3_resource = boto3.resource('s3')
    my_bucket = s3_resource.Bucket(os.environ.get('S3_BUCKET_NAME'))
    files = my_bucket.objects.filter(Prefix=str('Alle Data/') + str(filename) + '/')
    filnavne = []
    Q = []
    H = []
    stationer = []
    for objects in files:
        sep = '_'  # The separator fx FLADBRO KRO_VANDFORING.csv.
        obj = objects.key
        obj = obj.removeprefix('Alle Data/' + str(filename) + '/')
        stationer.append(obj)
    one_group = [];

STATQ/templates/program/QH_results.html
{% extends "layout.html" %}
{% block content %}
<ul class="nav nav-pills nav-justified" style="  background-color: rgba(1,1,1, 0.25); border-radius: .25vw;">
    <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#QH" style="color: white; font-size: 2.5vmin">QH
        KURVER</a></li>

</ul>
<div class="tab-pane fade" id="QH">
    <div class="plot-content" id="rawplot" style="border-radius: 0.25vw">
        <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
        <script type='text/javascript'>
            var graphs = {{graphJSONQH | safe}};
            var layout = { autosize: true };
            var config = { responsive: true, 'displaylogo': false, modeBarButtonsToRemove: ['hoverClosestCartesian', 'hoverCompareCartesian', 'toggleSpikelines'], 'displayModeBar': true};
            Plotly.setPlotConfig(config)
            Plotly.plot('rawplot', graphs, layout, config );


        </script>
    </div>
</div>
{% endblock content %}

STATQ/templates/program/database.html
{% extends "layout.html" %}
{% block content %}
<body>
<div class="content-section" style="">
    <h2 style="font-size: 3vmin;"><u style="color: #004b8d; font-weight: bold; text-decoration-color:gainsboro">
        Database </u></h2>
    <ul id="myMenu" style="list-style-type: none">
        <input id="mySearch" onkeyup="myFunction()" placeholder="Søg efter station.." style="font-size: 4vmin"
               title="Type in a category" type="text">

        <div class="content-section"
             style="float: left; overflow: scroll; width:100%; background-color: transparent; height: 77vh">

            {% for file in Q_files %}
            <li><a href="{{ url_for('program.station_files', filename=file) }}"
                   style="font-size:2vmin; margin: 0.5vmin 0">{{ file }} </a></li>
            {% endfor %}
        </div>
    </ul>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
        $(document).ready(function(){
            $("#fil-holder").change(function(){
                document.getElementById("Span-id").innerHTML = document.getElementById("fil-holder").files[0].name;
            });
        });
    function myFunction() {
      var input, filter, ul, li, a, i;
      input = document.getElementById("mySearch");
      filter = input.value.toUpperCase();
      ul = document.getElementById("myMenu");
      li = ul.getElementsByTagName("li");
      for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
          li[i].style.display = "";
        } else {
          li[i].style.display = "none";
        }
      }
    }


</script>

</body>
{% endblock content %}

STATQ/templates/program/help.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <h2 style="font-size: 5vmin;"><u style="color: #004b8d; font-weight: bold; text-decoration-color:gainsboro">
        Hjælp </u></h2>
    <p style="color: black; font-size: 2vmin;">Her finder du svar på problemer, som kan opstå under brug af STATQ.
    <p style="font-weight: bold; font-size: 2vmin">STATQ kan ikke læse min fil, hvad gør jeg?</p>
    <p style="margin-left: .5vw; margin-top: 0.01vh; font-size: 1.7vmin">STATQ udnytter, at alle data fra OdaForAlle har
        den overordnede samme struktur. Derfor er det vigtigt, at filer som skal bearbejdes af STATQ ikke er blevet
        ændret efter du har hentet dem fra OdaForAlle.au.dk. STATQ registrerer tre typer fejl:</p>
    <div style="text-indent: .5vw; margin-bottom: 0.5vh">
        <li style="font-size: 1.7vmin"><b>Fejlkode 0:</b> Filen er tom. Tjek at filen indeholder data</li>
        <li style="font-size: 1.7vmin"><b>Fejlkode 1:</b> Filens dato-format er blevet ændret. Skal angives YYYYMMDD
            (f.eks. 1. december 2020 --> 20201201)
        </li>
        <li style="font-size: 1.7vmin"><b> Fejlkode 2:</b> Filens kolonne-navne er blevet ændret. Filen kan kun læses,
            hvis originale kolonnenavne bevares.
        </li>
    </div>
    <p style="margin-left: .5vw; margin-top: 0.01vh; font-size: 1.7vmin"> Opstår en anden fejl, som ikke umiddelbart kan
        løses, modtages henvendelser gerne på LMS@srbat.dk.</p>
    <p style="font-weight: bold; font-size: 2vmin">
        Kan jeg uploade filer fra andre databaser (f.eks. Vandportalen eller Danmarks Miljøportal) til STATQ?
    </p>
    <p style="margin-left: .5vw;font-size: 1.7vmin"> STATQ understøtter i øjeblikket kun direkte import af filer fra
        OdaForAlle. Ønskes data af andet ophav at anvendes, kan en fil manuelt opstilles, således fil-strukturen
        opfyldes. </p>
    </ol>
</div>
{% endblock content %}

STATQ/templates/program/one_station_file.html
{% extends "layout.html" %}
{% block content %}
<body>
<div class="content-section" style="">
    <h2 style="font-size: 5vmin;"><u style="color: #004b8d; font-weight: bold; text-decoration-color:gainsboro"> {{
        Vandloeb }} </u></h2>
    {% for station, H_name, H_filename, Q_name, Q_filename, QH_name in grouped %}
    <h3> {{ station }}</h3>
    <legend class="file-boxes">{{ H_name }}

        <button class="btn btn-primary"
                onclick="window.location.href='{{ url_for('program.proces_databasefile', filename=H_filename, Vandloeb = Vandloeb) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float:right"
                type="button">
            <svg class="bi bi-graph-up" fill="currentColor" height="1.8vh" viewBox="0 0 16 16"
                 width="1.8vw" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
    </legend>
    <legend class="file-boxes"> {{ Q_name }}
        <button class="btn btn-primary"
                onclick="window.location.href='{{ url_for('program.proces_databasefile', filename=Q_filename, Vandloeb = Vandloeb) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float:right"
                type="button">
            <svg class="bi bi-graph-up" fill="currentColor" height="1.8vh" viewBox="0 0 16 16"
                 width="1.8vw" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
    </legend>
    <legend class="file-boxes"> {{ QH_name }}
        <button class="btn btn-primary"
                onclick="window.location.href='{{ url_for('program.proces_databaseQH', Q_file=Q_filename, H_file=H_filename, Vandloeb = Vandloeb) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float:right"
                type="button">
            <svg class="bi bi-graph-up" fill="currentColor" height="1.8vh" viewBox="0 0 16 16"
                 width="1.8vw" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
    </legend>
    {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
        $(document).ready(function(){
            $("#fil-holder").change(function(){
                document.getElementById("Span-id").innerHTML = document.getElementById("fil-holder").files[0].name;
            });
        });


</script>
</body>
{% endblock content %}

STATQ/templates/program/proces_file.html
{% extends "layout.html" %}
{% block content %}
<body>
<div class="content-section" style="">
    <h2 style="font-size: 3vmin;"><u style="color: #004b8d; font-weight: bold; text-decoration-color:gainsboro">
        Filer </u></h2>

    <form action="" enctype="multipart/form-data" method="POST"
          style="display: flex; margin-bottom: 3vh; margin-right: .5vw">

        <div class="file-drop-area" id="file-drop-area-id">
            <span class="fake-btn">Vælg fil</span>
            <span class="file-msg" id="Span-id">Eller træk filen ind i feltet</span>
            <input class="file-input" id="fil-holder" name="myFile" type="file">
        </div>
        <a style="position: relative; top: 0vh; left: 0.5vw; right: 1vw; ">
            <input onclick="window.location.href='{{ url_for('program.upload_file', filename=myFile) }}'"
                   style="height: 100%; border-radius: 0.5vw" type="submit"
                   value="Upload">
        </a>
    </form>
    {% if filenames %}
    {% for file in filenames %}
    <legend class="file-boxes">{{ file }}
        <button class="btn btn-primary"
                onclick="window.location.href='{{ url_for('program.proces_file', filename=file) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float:right"
                type="button">
            <svg class="bi bi-graph-up" fill="currentColor" height="1.8vh" viewBox="0 0 16 16"
                 width="1.8vw" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
        <button class="btn btn-danger"
                onclick="window.location.href='{{ url_for('program.delete_file', filename=file) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float: right">
            <svg class="bi bi-trash" fill="currentColor" height="1.8vh" viewBox="0 0 16 16" width="1.8vw"
                 xmlns="http://www.w3.org/2000/svg">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
    </legend>
    {% endfor %}
    {% endif %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
        $(document).ready(function(){
            $("#fil-holder").change(function(){
                document.getElementById("Span-id").innerHTML = document.getElementById("fil-holder").files[0].name;
            });
        });


</script>
</body>
{% endblock content %}

STATQ/templates/program/station_files.html
{% extends "layout.html" %}
{% block content %}
<body>
<div class="content-section" style="overflow: scroll">
    <h2 style="font-size: 5vmin;"><u style="color: #004b8d; font-weight: bold; text-decoration-color:gainsboro"> {{
        Vandloeb }} </u></h2>
    {% for station, H_name, H_filename, Q_name, Q_filename, QH_name in grouped %}
    <h3> {{ station }}</h3>
    <legend class="file-boxes">{{ H_name }}

        <button class="btn btn-primary"
                onclick="window.location.href='{{ url_for('program.proces_databasefile', filename=H_filename, Vandloeb = Vandloeb) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float:right"
                type="button">
            <svg class="bi bi-graph-up" fill="currentColor" height="1.8vh" viewBox="0 0 16 16"
                 width="1.8vw" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
    </legend>
    <legend class="file-boxes"> {{ Q_name }}
        <button class="btn btn-primary"
                onclick="window.location.href='{{ url_for('program.proces_databasefile', filename=Q_filename, Vandloeb = Vandloeb) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float:right"
                type="button">
            <svg class="bi bi-graph-up" fill="currentColor" height="1.8vh" viewBox="0 0 16 16"
                 width="1.8vw" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
    </legend>
    <legend class="file-boxes"> {{ QH_name }}
        <button class="btn btn-primary"
                onclick="window.location.href='{{ url_for('program.proces_databaseQH', Q_file=Q_filename, H_file=H_filename, Vandloeb = Vandloeb) }}'"
                style="width:  4vw; height: 4vh; font-size:  1vmin; float:right"
                type="button">
            <svg class="bi bi-graph-up" fill="currentColor" height="1.8vh" viewBox="0 0 16 16"
                 width="1.8vw" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 0h1v15h15v1H0V0Zm14.817 3.113a.5.5 0 0 1 .07.704l-4.5 5.5a.5.5 0 0 1-.74.037L7.06 6.767l-3.656 5.027a.5.5 0 0 1-.808-.588l4-5.5a.5.5 0 0 1 .758-.06l2.609 2.61 4.15-5.073a.5.5 0 0 1 .704-.07Z"
                      fill-rule="evenodd"/>
            </svg>
        </button>
    </legend>
    {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
        $(document).ready(function(){
            $("#fil-holder").change(function(){
                document.getElementById("Span-id").innerHTML = document.getElementById("fil-holder").files[0].name;
            });
        });


</script>
</body>
{% endblock content %}

STATQ/templates/program/upload_file.html
{% extends "layout.html" %}
{% block content %}

{% endblock content %}